import Head from "next/head";
import Messaging from "../components/Messaging/Messaging";
import styles from "../styles/Home.module.scss";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "../data/firebase";
import SignIn from "../components/SignIn/SignIn";
import SignOut from "../components/SignOut/SignOut";

export default function Home() {
  const [user] = useAuthState(auth);
  return (
    <div className={styles.container}>
      <h1>Message Box</h1>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user ? (
        <>
          <Messaging />
          <SignOut />
        </>
      ) : (
        <SignIn />
      )}
    </div>
  );
}
